### ISSUE TITLE
Improving performance for large data

### ISSUE THREAD

**Issue by RSchwinn** [dgkf/shinyDataFilter#11]
1. You are amazing.
2. Is there anyway to reduce the number of columns that a user can select from?
3. Would this make it faster?

I want to apply this to large data frames (dozens of variables, millions of rows), but the preprocessing overhead is too much. Is there anything to be done?

**Comment by dgkf** [comment]
Hi @RSchwinn, tackling your items (slightly out-of-order)

> 1. You are amazing.

thank you :blush: 

>  3. Would this make it faster? I want to apply this to large data frames (dozens of variables, millions of rows), but the preprocessing overhead is too much. Is there anything to be done?

It's not surprising that large datasets will start to bog down the module. The module doesn't do anything fancy to cache distributions or anything like that, so you end up recalculating every distribution with each selection. This is fine for small data, but can definitely bog down any app with larger data (certainly with millions of rows).

To help narrow down the possible performance factors, can you expand a bit on what slowness you're seeing? Are there specific actions that perform poorly (selecting a column, updating a filter when there are multiple filters already created)? Are there specific column data types (numeric, string, factor, etc) where the slowness is most pronounced? 

> 2. Is there anyway to reduce the number of columns that a user can select from?

Following on from 3, I think this could help alleviate slowness when selecting a column, but downstream components are only calculated for the columns that are listed, so reducing the total number of available columns would probably not help solve this (at least not without some more systemic changes to the way the package works, more below).

**Comment by RSchwinn** [comment]
Response in under hour, what a role-model! (Please excuse my flattery; but you keep earning it.)

> (1) ... can you expand a bit on what slowness you're seeing? Are there specific actions that perform poorly (selecting a column, updating a filter when there are multiple filters already created)? Are there specific column data types (numeric, string, factor, etc) where the slowness is most pronounced?

I was wrong. It is not slow, even when filtering GBs of data. The hang up was an unrelated package update.^[On each system that I installed your app, I was required to upgrade several other packages. **scales**'s label_number_si function was recently knee-capped (to roughly 1/15th the speed) and replaced by a new function label_number(scale_cut = cut_short_scale())(). I apologize for taking your time for a non-existent issue.]

SEPARATE QUERY:
When working with a large dataset (with many important but ancillary variables) it would be hugely valuable to end users if designers could limit which variables are available for filtering. For example, if it were possible to feed a small vector of variables into the callModule function, so that only those variables could be filtered, but the others could still be used in later calculations -> this would make some of my applications much more accessible. Given that speed is not a factor after all, the only motivation would be to avoid overwhelming end-users.

AND SUGGESTION:
I think the only reason your package isn't one of the most popular on CRAN among shiny users is that the documentation simply references the following command:

```library(shiny)
shinyAppFile(system.file("examples", "basic_app", "app.R", package = "shinyDataFilter"))
```

The shiny shinyAppFile() function doesn't work for me in some environments, such as on RStudio Workbench, and even if you get the app running, implementing it still requires digging through the repository. I think that if you simply put the code below from **shiny_data_filter_ui** in your README.md and in every help file (and enable my suggestion above), this package will become a cornerstone of Shiny.

```
## Not run: 
[library](https://rdrr.io/r/base/library.html)(shiny)
[library](https://rdrr.io/r/base/library.html)(shinyDataFilter)

[library](https://rdrr.io/r/base/library.html)(dplyr)  # for data preprocessing and example data

# prep a new data.frame with more diverse data types
starwars2 <- starwars %>%
  mutate_if(~[is.numeric](https://rdrr.io/r/base/numeric.html)(.) && [all](https://rdrr.io/r/base/all.html)([Filter](https://rdrr.io/r/base/funprog.html)([Negate](https://rdrr.io/r/base/funprog.html)([is.na](https://rdrr.io/r/base/NA.html)), .) %% 1 == 0), [as.integer](https://rdrr.io/r/base/integer.html)) %>%
  mutate_if(~[is.character](https://rdrr.io/r/base/character.html)(.) && [length](https://rdrr.io/r/base/length.html)([unique](https://rdrr.io/r/base/unique.html)(.)) <= 25, [as.factor](https://rdrr.io/r/base/factor.html)) %>%
  mutate(is_droid = species == "Droid") %>%
  select([name](https://rdrr.io/r/base/name.html), gender, [height](https://rdrr.io/r/grid/grid-internal.html), mass, hair_color, eye_color, vehicles, is_droid)

# create some labels to showcase column select input
[attr](https://rdrr.io/r/base/attr.html)(starwars2$[name](https://rdrr.io/r/base/name.html), "label")     <- "name of character"
[attr](https://rdrr.io/r/base/attr.html)(starwars2$gender, "label")   <- "gender of character"
[attr](https://rdrr.io/r/base/attr.html)(starwars2$[height](https://rdrr.io/r/grid/grid-internal.html), "label")   <- "height of character in centimeters"
[attr](https://rdrr.io/r/base/attr.html)(starwars2$mass, "label")     <- "mass of character in kilograms"
[attr](https://rdrr.io/r/base/attr.html)(starwars2$is_droid, "label") <- "whether character is a droid"

ui <- fluidPage(
  titlePanel("Filter Data Example"),
  fluidRow(
    column(8, 
      verbatimTextOutput("data_summary"),
      verbatimTextOutput("data_filter_code")),
    column(4, [shiny_data_filter_ui](https://rdrr.io/github/dgkf/shinyDataFilter/man/shiny_data_filter_ui.html)("data_filter"))))

server <- [function](https://rdrr.io/r/base/function.html)(input, output, session) {
  filtered_data <- callModule(
    [shiny_data_filter](https://rdrr.io/github/dgkf/shinyDataFilter/man/shiny_data_filter.html), 
    "[data](https://rdrr.io/r/utils/data.html)_filter", 
    data = starwars2,
    verbose = [FALSE](https://rdrr.io/r/base/logical.html))
  
  output$data_filter_code <- renderPrint({
    [cat](https://rdrr.io/r/base/cat.html)([gsub](https://rdrr.io/r/base/grep.html)("%>%", "%>% \n ", 
      [gsub](https://rdrr.io/r/base/grep.html)("\\s{2,}", " ", 
        [paste0](https://rdrr.io/r/base/paste.html)(
          [capture.output](https://rdrr.io/r/utils/capture.output.html)([attr](https://rdrr.io/r/base/attr.html)(filtered_data(), "code")), 
          collapse = " "))
    ))
  })
  
  output$data_summary <- renderPrint({
    if ([nrow](https://rdrr.io/r/base/nrow.html)(filtered_data())) [show](https://rdrr.io/r/methods/show.html)(filtered_data())
    [else](https://rdrr.io/r/base/Control.html) "No data available"
  })
}

shinyApp(ui = ui, server = server)

## End(Not run) ```

**Comment by dgkf** [comment]
Thanks for the follow-up, @RSchwinn. Glad (and maybe a bit surprised) to hear that the package is holding up for gigabyte-sized data.

> When working with a large dataset (with many important but ancillary variables) it would be hugely valuable to end users if designers could limit which variables are available for filtering.

Yeah - I think this would be a reasonably minor change. I'll file a feature issue for this. Unfortunately, it's pretty rare that I do shiny work these days, so it's a bit lower on my priority list. Nevertheless, I think the feature is pretty minor and I'll make an effort to explore it and roll it in reasonably soon. 

> The shiny shinyAppFile() function doesn't work for me in some environments

Thank you for reporting this! I'll see if I can clean this up.

---

I'm going to mark this as closed since the performance issues seem to be unrelated. Please continue to file issues as you encounter them.

**Comment by dgkf** [comment]
Sorry for the delay, but better late than never

> Is there anyway to reduce the number of columns that a user can select from?

Now there is!

You can use the `choices` parameter to specify which columns should be filterable

https://github.com/dgkf/shinyDataFilter/blob/6c64451774bf2b95819027496d1dc417567f51e0/inst/examples/basic_app/app.R#L29-L35
