### ISSUE TITLE
"add Filter" button not populated  when using shiny >= 1.8.0

### ISSUE THREAD

**Issue by SimonCoulombe** [dgkf/shinyDataFilter#25]
I reverted to `devtools::install_version("shiny", version = "1.7.4.1")`  and that fixed it.

edit:  also need to comment that this is a beautiful module! I'm need to work with tables on an SQL server that I interact with using dbplyr, hopefully the "main" features will work.

**Comment by dgkf** [comment]
Thanks for reporting and for the kind words :smile: 

I can't say I'm too active in developing this package these days. Should inspiration strike, I'll see if I can sort this one out. That said, my priorities are usually elsewhere these days so if anyone out there is interested in implementing a fix, your contribution would be very welcome.
