### ISSUE TITLE
Document minimum steps to use the functionality

### ISSUE THREAD

**Issue by chintanp** [dgkf/shinyDataFilter#5]
This is a great idea, and after seeing this submission in the Shiny Apps 2020 contest, I have been irking to use this. Now with a project in hand, I am wondering what are the minimum steps needed to create a shinyDataFilter type functionality around my table.

**Comment by dgkf** [comment]
After a long delay, I've added a small helper to pull up the example file to showcase how you can add it to an app. Or, on GitHub you can head to the `inst/examples` directory to see an example app.
